name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # ativa apenas quando uma tag que começa com v for criada

jobs:
  build-and-publish:
    name: Build and publish Python 🐍 distribution to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install build tools
        run: python -m pip install --upgrade build

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
